import type { TortillaIngredientModifier } from "./types";

export const OPTIONAL_INGREDIENTS: TortillaIngredientModifier[] = [
  // Vegetables
  {
    ingredientId: "onion",
    category: "vegetables",
    name: { es: "Cebolla dulce", en: "Sweet Onion", de: "Süße Zwiebel" },
    icon: "Utensils",
    defaultUnit: "g",
    defaultQuantity: 180,
    stepIncrement: 20,
    minQuantity: 40,
    maxQuantity: 400,
    taxonomySlug: { es: "cebolla", en: "onion", de: "zwiebel" },
    effect: {
      moisture: 2,
      fat: 0,
      sweetness: 2,
      salt: 0,
    },
    cookingAdvice: {
      es: "Tu cebolla aporta humedad y dulzor natural. Pocha a fuego lento hasta caramelizar ligeramente antes de mezclar con el huevo.",
      en: "Your onion adds moisture and natural sweetness. Poach slowly until translucent or lightly caramelized before adding to egg.",
      de: "Ihre Zwiebel sorgt für Feuchtigkeit und natürliche Süße. Langsam dünsten, bis sie glasig ist, bevor das Ei hinzugefügt wird.",
    },
  },
  {
    ingredientId: "green_pepper",
    category: "vegetables",
    name: { es: "Pimiento verde", en: "Green Pepper", de: "Grüne Paprika" },
    icon: "Carrot",
    defaultUnit: "g",
    defaultQuantity: 80,
    stepIncrement: 10,
    minQuantity: 20,
    maxQuantity: 200,
    taxonomySlug: { es: "pimiento-verde", en: "green-pepper", de: "gruener-paprika" },
    effect: {
      moisture: 1,
      fat: 0,
      sweetness: 0,
      salt: 0,
    },
    cookingAdvice: {
      es: "El pimiento verde añade frescura y notas herbáceas. Sofríelo junto a la patata para ablandar la piel.",
      en: "Green pepper adds crisp freshness and herbal notes. Sauté along with potatoes to soften its skin.",
      de: "Grüne Paprika verleiht Frische und krautige Noten. Zusammen mit den Kartoffeln anbraten.",
    },
  },
  {
    ingredientId: "red_pepper",
    category: "vegetables",
    name: { es: "Pimiento rojo", en: "Red Pepper", de: "Rote Paprika" },
    icon: "Flame",
    defaultUnit: "g",
    defaultQuantity: 80,
    stepIncrement: 10,
    minQuantity: 20,
    maxQuantity: 200,
    taxonomySlug: { es: "pimiento-rojo", en: "red-pepper", de: "roter-paprika" },
    effect: {
      moisture: 1,
      fat: 0,
      sweetness: 1,
      salt: 0,
    },
    cookingAdvice: {
      es: "El pimiento rojo aporta color y dulzor suave. Pícalo en dados finos y póchalo bien para evaporar el exceso de agua.",
      en: "Red pepper adds vivid color and subtle sweetness. Dice finely and cook thoroughly to evaporate excess water.",
      de: "Rote Paprika bringt Farbe und milde Süße. Fein würfeln und gut durchgaren.",
    },
  },
  {
    ingredientId: "garlic",
    category: "vegetables",
    name: { es: "Ajo confitado", en: "Poached Garlic", de: "Knoblauch" },
    icon: "Sparkles",
    defaultUnit: "g",
    defaultQuantity: 15,
    stepIncrement: 5,
    minQuantity: 5,
    maxQuantity: 40,
    taxonomySlug: { es: "ajo", en: "garlic", de: "knoblauch" },
    effect: {
      moisture: 0,
      fat: 0,
      sweetness: 1,
      salt: 0,
    },
    cookingAdvice: {
      es: "El ajo infusiona el aceite durante el pochado. Retíralo antes de que se dore demasiado para evitar amargor.",
      en: "Garlic infuses the frying oil with aroma. Remove before it browns too deeply to prevent bitterness.",
      de: "Knoblauch aromatisiert das Olivenöl. Vor dem dunklen Anbraten entfernen, um Bitterkeit zu vermeiden.",
    },
  },
  {
    ingredientId: "mushrooms",
    category: "vegetables",
    name: { es: "Champiñones / Setas", en: "Mushrooms", de: "Pilze" },
    icon: "Leaf",
    defaultUnit: "g",
    defaultQuantity: 100,
    stepIncrement: 20,
    minQuantity: 30,
    maxQuantity: 250,
    taxonomySlug: { es: "champinones", en: "mushrooms", de: "pilze" },
    effect: {
      moisture: 2,
      fat: 0,
      sweetness: 0,
      salt: 0,
    },
    cookingAdvice: {
      es: "Los champiñones sueltan mucha agua. Saltéalos en sartén aparte a fuego vivo hasta saltear y evaporar todo el jugo.",
      en: "Mushrooms release high moisture. Pre-cook in a separate hot pan to evaporate water before folding into egg.",
      de: "Pilze geben viel Wasser ab. Vorab in einer heißen Pfanne anbraten, bis alle Flüssigkeit verdampft ist.",
    },
  },
  {
    ingredientId: "spinach",
    category: "vegetables",
    name: { es: "Espinacas frescas", en: "Fresh Spinach", de: "Frischer Spinat" },
    icon: "Sprout",
    defaultUnit: "g",
    defaultQuantity: 80,
    stepIncrement: 15,
    minQuantity: 20,
    maxQuantity: 200,
    taxonomySlug: { es: "espinacas", en: "spinach", de: "spinat" },
    effect: {
      moisture: 2,
      fat: 0,
      sweetness: 0,
      salt: 0,
    },
    cookingAdvice: {
      es: "Marchita las espinacas brevemente y escúrrelas con esmero para no diluir el ligazón del huevo.",
      en: "Wilt spinach lightly and squeeze thoroughly dry so it does not dilute the egg binder.",
      de: "Spinat kurz dünsten und gründlich ausdrücken, um das Ei nicht zu verwässern.",
    },
  },

  // Meat
  {
    ingredientId: "chorizo",
    category: "meat",
    name: { es: "Chorizo artesanal", en: "Artisanal Chorizo", de: "Chorizo" },
    icon: "Beef",
    defaultUnit: "g",
    defaultQuantity: 60,
    stepIncrement: 10,
    minQuantity: 20,
    maxQuantity: 150,
    taxonomySlug: { es: "chorizo", en: "chorizo", de: "chorizo" },
    effect: {
      moisture: 0,
      fat: 2,
      sweetness: 0,
      salt: 2,
    },
    cookingAdvice: {
      es: "Saltea el chorizo brevemente para soltar su aceite pimentonado; incorpóralo justo antes del cuajado.",
      en: "Sauté chorizo briefly to render paprika-infused oil; fold in right before setting in the pan.",
      de: "Chorizo kurz anbraten, um das Paprikaöl freizusetzen; kurz vor dem Stocken untermischen.",
    },
  },
  {
    ingredientId: "ham",
    category: "meat",
    name: { es: "Jamón ibérico / Serrano", en: "Cured Ham", de: "Schinken" },
    icon: "Drumstick",
    defaultUnit: "g",
    defaultQuantity: 50,
    stepIncrement: 10,
    minQuantity: 20,
    maxQuantity: 120,
    taxonomySlug: { es: "jamon", en: "ham", de: "schinken" },
    effect: {
      moisture: 0,
      fat: 1,
      sweetness: 0,
      salt: 2,
    },
    cookingAdvice: {
      es: "Añade el jamón al final mezclándolo con el huevo fuera del fuego para que no se endurezca con el calor.",
      en: "Add cured ham off the heat when mixing with egg to prevent it from hardening.",
      de: "Schinken erst am Ende abseits der Hitze unter das Ei rühren, damit er zart bleibt.",
    },
  },
  {
    ingredientId: "bacon",
    category: "meat",
    name: { es: "Panceta / Bacon crujiente", en: "Crispy Bacon", de: "Speck" },
    icon: "Ham",
    defaultUnit: "g",
    defaultQuantity: 60,
    stepIncrement: 10,
    minQuantity: 20,
    maxQuantity: 150,
    taxonomySlug: { es: "bacon", en: "bacon", de: "speck" },
    effect: {
      moisture: 0,
      fat: 2,
      sweetness: 0,
      salt: 2,
    },
    cookingAdvice: {
      es: "Dora la panceta antes para extraer la grasa y dar un toque crujiente inolvidable.",
      en: "Crisp up bacon beforehand to render fat and add an unforgettable crunch.",
      de: "Speck vorher knusprig auslassen, um das Fett zu nutzen und Knusprigkeit zu verleihen.",
    },
  },

  // Dairy
  {
    ingredientId: "cheese",
    category: "dairy",
    name: { es: "Queso curado / Tetilla / Manchego", en: "Cheese", de: "Käse" },
    icon: "PieChart",
    defaultUnit: "g",
    defaultQuantity: 70,
    stepIncrement: 10,
    minQuantity: 20,
    maxQuantity: 180,
    taxonomySlug: { es: "queso", en: "cheese", de: "kaese" },
    effect: {
      moisture: 0,
      fat: 2,
      sweetness: 0,
      salt: 1,
    },
    cookingAdvice: {
      es: "Fundirás el queso en el calor residual de la patata antes de verter el huevo para crear hilos cremosos.",
      en: "Melt cheese into residual heat of hot cooked potatoes before adding raw eggs for creamy strands.",
      de: "Käse in der Restwärme der heißen Kartoffeln schmelzen lassen, für eine cremige Textur.",
    },
  },
  {
    ingredientId: "milk",
    category: "dairy",
    name: { es: "Toque de leche / Nata", en: "Splash of Milk/Cream", de: "Milch / Sahne" },
    icon: "Milk",
    defaultUnit: "ml",
    defaultQuantity: 30,
    stepIncrement: 5,
    minQuantity: 10,
    maxQuantity: 80,
    taxonomySlug: { es: "leche", en: "milk", de: "milch" },
    effect: {
      moisture: 1,
      fat: 1,
      sweetness: 0,
      salt: 0,
    },
    cookingAdvice: {
      es: "Un chorrito de leche o nata al batir el huevo aporta esponjosidad y retrasa ligeramente la coagulación.",
      en: "A splash of milk whisked into eggs provides fluffiness and slightly slows down coagulation.",
      de: "Ein Schluck Milch im Ei sorgt für Lockerheit und verzögert das Stocken leicht.",
    },
  },

  // Other
  {
    ingredientId: "leftovers",
    category: "other",
    name: { es: "Restos de guiso / Sobras gourmet", en: "Gourmet Leftovers", de: "Reste" },
    icon: "Box",
    defaultUnit: "g",
    defaultQuantity: 100,
    stepIncrement: 20,
    minQuantity: 30,
    maxQuantity: 250,
    taxonomySlug: { es: "sobras", en: "leftovers", de: "reste" },
    effect: {
      moisture: 1,
      fat: 1,
      sweetness: 0,
      salt: 1,
    },
    cookingAdvice: {
      es: "Atempera las sobras previamente para no bajar la temperatura del huevo durante el batido.",
      en: "Warm leftover dishes slightly first so they don't drop the egg coagulation temperature.",
      de: "Reste vorher erwärmen, um die Gerinnungstemperatur des Eies nicht zu senken.",
    },
  },
  {
    ingredientId: "seasonal",
    category: "other",
    name: { es: "Ingrediente de temporada (Espárragos/Setas)", en: "Seasonal Produce", de: "Saisonale Zutaten" },
    icon: "Sun",
    defaultUnit: "g",
    defaultQuantity: 80,
    stepIncrement: 10,
    minQuantity: 20,
    maxQuantity: 200,
    taxonomySlug: { es: "ingredientes-temporada", en: "seasonal-ingredients", de: "saisonale-zutaten" },
    effect: {
      moisture: 1,
      fat: 0,
      sweetness: 1,
      salt: 0,
    },
    cookingAdvice: {
      es: "Saltea brevemente las verduras de temporada a fuego vivo para mantener textura crujiente y color vivo.",
      en: "Sauté seasonal greens quickly over high heat to preserve crunch and vibrant color.",
      de: "Saisonales Gemüse kurz scharf anbraten, um Biss und Farbe zu bewahren.",
    },
  },
];

export function getIngredientModifier(id: string): TortillaIngredientModifier | undefined {
  return OPTIONAL_INGREDIENTS.find((i) => i.ingredientId === id);
}
